### ISSUE TITLE
Results of testing vagrant branch with Docker Machine

### ISSUE THREAD

**Issue by wizonesolutions** [thom8/beetbox-docker#1]
So I'm trying out the experimental `vagrant` branch.

I decided the simplest way to use this was to create my own branch into which I commit my private changes. This way, I can still pull in upstream changes.

I also needed to edit the Vagrantfile to make use of my existing Docker Machine VM. Namely, tweaking the SSH configuration so Vagrant could actually get in:

``` ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'fileutils'
require 'yaml'

Vagrant.require_version '>= 1.8.5'

Vagrant.configure("2") do |config|

  ssh_port = "2224"

  config.vm.synced_folder ".", "/var/beetbox"

  config.vm.define "beetbox", primary: true do |bb|
    bb.vm.provider "docker" do |d|
      d.name = "beetbox"
      d.build_dir = ".beetbox"
      d.ports = ["80:80", "#{ssh_port}:22"]
      d.force_host_vm = false
      d.has_ssh = true
      d.link("beetbox_db:beetbox_db")
    end

    bb.ssh.username = "docker"
    bb.ssh.insert_key = false
    bb.ssh.host = "10.211.55.108"
    bb.ssh.port = 22
    bb.ssh.private_key_path = "~/.docker/machine/machines/prl-dev/id_rsa"
    bb.ssh.shell = "/bin/sh"

    bb.vm.provision "beetbox", type: "shell", inline: %q(docker exec -it beetbox script -q -c '/bin/bash -c "export BEET_PROFILE=docker && /beetbox/provisioning/beetbox.sh"')
    bb.vm.provision "php-fpm", type: "shell", inline: %q(docker exec -it beetbox service php5.6-fpm start)

  end

  config.vm.define "db" do |db|
    db.vm.provider "docker" do |d|
      d.name = "beetbox_db"
      d.image = "mariadb"
      d.ports = ["3306:3306"]
      d.expose = ["3306"]
      d.force_host_vm = false
      d.env = {
        'MYSQL_ROOT_PASSWORD' => 'root',
        'MYSQL_DATABASE' => 'beetbox',
        'MYSQL_USER' => 'beetbox',
        'MYSQL_PASSWORD' => 'beetbox'
      }
    end
  end

end
```

However, I couldn't actually make it work in the end. You can see I played with the provisioning commands, but they wouldn't run. I always got `=> beetbox: input device is not a TTY`, and Vagrant would consider this an error and bail.

Thought I'd document my attempt at least.

**Comment by thom8** [comment]
Had a quick look -- you'd need to configure the SSH conf outside the container definitions, the SSH config changes above are for the actual beetbox container.

eg.

```
  config.ssh.insert_key = true
  config.ssh.username = 'docker'
  config.ssh.password = 'tcuser'
  config.ssh.guest_port = 2222
  config.ssh.port = 22
  config.ssh.host = '127.0.0.1'
```

This is concerning with anything boot2docker related --
https://github.com/mitchellh/boot2docker-vagrant-box/issues/79#issuecomment-245459209

However this looks promising -- https://github.com/leighmcculloch/vagrant-docker-compose
so vagrant would just drive docker compose..

**Comment by wizonesolutions** [comment]
That Compose plugin looks neat. Maybe that is the way.

I think that Machine/boot2docker will be around for a bit still. The macOS file performance is still too bad. They'd lose a lot of mindshare shoving that down our throats (IMO, could be wrong).

**Comment by thom8** [comment]
The main issue is that Machine/boot2docker has been superseded by D4M/D4W so support will be limited, I'm sure the current file sync issues will be addressed but it seems they have higher priorities ATM.

https://forums.docker.com/t/file-access-in-mounted-volumes-extremely-slow-cpu-bound/8076/197

BTW I'm really enjoying D4M for testing and local CI where file syncing is not required so will probably just wait until this is fixed rather than implementing one of the many workarounds which are usually OS specific.
